package conf

const (
	GetUserActivityAPI       = "/GetUserActivity"
	GetUserActivityDetailAPI = "/GetUserActivityDetail"
	PhoneGetActList          = "/PhoneGetActList"
	PhoneGetActDetailAPI     = "/PhoneGetActDetail"
	// PhoneGetActRankAPI       = "/PhoneGetActRank"
	PhoneSearchActAPI    = "/PhoneSearchAct"
	PhoneSearchStuRank   = "/PhoneSearchStuRank"
	GetActivityAPI       = "/GetActivity"
	GetActivityDetailAPI = "/GetActivityDetail"
	GetActivityRankAPI   = "/GetActivityRank"
	UpdateActivityAPI    = "/UpdateActivity"
	DeleteActivityAPI    = "/DeleteActivity"
	AddActivityAPI       = "/AddActivity"
	SearchActivityAPI    = "/SearchActivity"
	PCSearchActivityAPI  = "/PCSearchActivity"
	GetRankAPI                 = "/GetRank"
	SearchRankAPI              = "/SearchRank"
	SearchRecordAPI            = "/SearchRecord"
	AddAdministrationAPI       = "/AddAdministration"
	GetAdministrationAPI       = "/GetAdministration"
	SearchAdministrationAPI    = "/SearchAdministration"
	AddUserInfoAPI             = "/AddUserInfo"
	GetUserInfoAPI             = "/GetUserInfo"
	AddUserScoreAPI            = "/AddUserScore"
	GetUserRankAPI             = "/GetUserRank"
	DeleteUserScoreAPI         = "/DeleteUserScore"
	GetUserRecordAPI           = "/GetUserRecord"
	WeChatLoginAPI             = "/WXLogin"
	GetCodeAPI                 = "/GetCode"
	ValiWXGZHAPI               = "/valiWXGZH"
	ManagerLoginAPI            = "/ManagerLogin"
	DeleteUserQualificationAPI = "/DeleteUserQualificationAPI"
	EndActivityAPI             = "/EndActivity"
	ImageUploadAPI             = "/ImageUpload"
	PcGetActivityDetailAPI     = "/PcGetActivityDetail"
	UploadAPI                  = "/upload"
	UploadedAPI                = "/uploaded/{category}"
	MockWeChatLoginAPI         = "/cMockWXlogin"
	GetMP4API                  = "/video/{category}"
	UploadMP4API               = "/uploadMP4"
)
